# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'iOS代码规范Demo' do
pod 'ReactiveCocoa','2.5'
end

target 'iOS代码规范DemoTests' do

end

target 'iOS代码规范DemoUITests' do

end

